export const SOURCE_CATALOG = [
  {
    id: "uschess",
    name: "US Chess Federation (TLA)",
    homepage: "https://new.uschess.org/upcoming-tournaments",
    type: "national",
  },
  {
    id: "chessresults",
    name: "Chess-Results.com",
    homepage: "https://chess-results.com/",
    type: "aggregator",
  },
  {
    id: "cca",
    name: "Continental Chess Association",
    homepage: "https://www.continentalchess.com/",
    type: "organizer",
  },
  {
    id: "charlottechesscenter",
    name: "Charlotte Chess Center",
    homepage: "https://www.charlottechesscenter.org/events",
    type: "organizer",
  },
  {
    id: "stlouischessclub",
    name: "Saint Louis Chess Club",
    homepage: "https://saintlouischessclub.org/events",
    type: "organizer",
  },
  {
    id: "chessearth",
    name: "Chess Earth Tournament Calendar",
    homepage: "https://chessearth.com/chess-calendar/",
    type: "aggregator",
  },
];

export const SEEDED_EVENTS = [
  {
    id: "uschess-stl-classic",
    name: "St. Louis Spring Swiss",
    startDate: "2026-03-14",
    endDate: "2026-03-15",
    city: "St. Louis",
    state: "MO",
    venue: "Saint Louis Chess Club",
    format: "5SS G/60 d5",
    summary:
      "Weekend US Chess-rated swiss with Open/U1900/U1600 sections and same-day pairings.",
    sourceId: "uschess",
    sourceUrl: "https://new.uschess.org/upcoming-tournaments",
    registrationUrl: "https://new.uschess.org/upcoming-tournaments",
    detailsUrl: "https://new.uschess.org/upcoming-tournaments",
    lat: 38.627,
    lon: -90.1994,
  },
  {
    id: "cca-chicago-class",
    name: "Chicago Class Championship",
    startDate: "2026-04-11",
    endDate: "2026-04-12",
    city: "Rosemont",
    state: "IL",
    venue: "Hyatt Regency O'Hare",
    format: "5SS 40/100 SD/30",
    summary: "Major CCA class event with blitz side event and guaranteed section prizes.",
    sourceId: "cca",
    sourceUrl: "https://www.continentalchess.com/",
    registrationUrl: "https://www.continentalchess.com/",
    detailsUrl: "https://www.continentalchess.com/",
    lat: 41.9742,
    lon: -87.9073,
  },
  {
    id: "ccc-norm-invitational",
    name: "Charlotte Summer GM/IM Invitational",
    startDate: "2026-05-20",
    endDate: "2026-05-25",
    city: "Charlotte",
    state: "NC",
    venue: "Charlotte Chess Center",
    format: "Round-robin norm groups",
    summary: "Norm event with live transmission and side swiss for local players.",
    sourceId: "charlottechesscenter",
    sourceUrl: "https://www.charlottechesscenter.org/events",
    registrationUrl: "https://www.charlottechesscenter.org/events",
    detailsUrl: "https://www.charlottechesscenter.org/events",
    lat: 35.2271,
    lon: -80.8431,
  },
  {
    id: "chessresults-bay-open",
    name: "Bay Area Open",
    startDate: "2026-06-06",
    endDate: "2026-06-07",
    city: "San Jose",
    state: "CA",
    venue: "San Jose Convention District",
    format: "4SS G/90 +30",
    summary: "Open Swiss featuring FIDE-rated sections and weekend schedule options.",
    sourceId: "chessresults",
    sourceUrl: "https://chess-results.com/",
    registrationUrl: "https://chess-results.com/",
    detailsUrl: "https://chess-results.com/",
    lat: 37.3382,
    lon: -121.8863,
  },
  {
    id: "slcc-rapid-night",
    name: "Friday Night Rapid",
    startDate: "2026-03-27",
    endDate: "2026-03-27",
    city: "St. Louis",
    state: "MO",
    venue: "World Chess Hall Campus",
    format: "6SS G/15 +10",
    summary: "One-night rapid tournament, beginner-friendly sections included.",
    sourceId: "stlouischessclub",
    sourceUrl: "https://saintlouischessclub.org/events",
    registrationUrl: "https://saintlouischessclub.org/events",
    detailsUrl: "https://saintlouischessclub.org/events",
    lat: 38.6367,
    lon: -90.2348,
  },
  {
    id: "chessearth-dallas-open",
    name: "Dallas Metro Open",
    startDate: "2026-04-25",
    endDate: "2026-04-26",
    city: "Dallas",
    state: "TX",
    venue: "North Dallas Conference Center",
    format: "5SS G/80 d5",
    summary: "Regional swiss with scholastic and adult sections running in parallel.",
    sourceId: "chessearth",
    sourceUrl: "https://chessearth.com/chess-calendar/",
    registrationUrl: "https://chessearth.com/chess-calendar/",
    detailsUrl: "https://chessearth.com/chess-calendar/",
    lat: 32.7767,
    lon: -96.797,
  },
];
